version: '3.10'

services:
  # FastAPI Backend
  ml-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - ml-network

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.6.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - ml-network

  # Optional: Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ml-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ml-backend
    restart: unless-stopped
    networks:
      - ml-network

volumes:
  qdrant_storage:
  redis_data:

networks:
  ml-network:
    driver: bridge